#!/usr/bin/python3.6

import argparse
import argcomplete
import sys
import os
import os.path as path



def get_deps(f, result=[]):
  if f == '': return result

  if path.isfile(f):
    f = path.dirname(f)

  files = os.listdir(f)
  
  if 'DEPS' in files:
    result.append(path.join(f, 'DEPS'))

  return get_deps(path.dirname(f), result)

def execute(args):
  results = get_deps(args.file)

  if len(results) == 0:
    print('No DEPS found')
    return

  if args.list:
    for result in results: print(result)
  else: print(results[0])

  if args.open:
    os.system(f'$EDITOR {results[0]}')

if __name__ == '__main__':
  parser = argparse.ArgumentParser(description="Find the DEPs files for a file.")

  parser.add_argument('file')
  parser.add_argument('--open', action='store_true')
  parser.add_argument('--list', action='store_true')

  argcomplete.autocomplete(parser)
  args = parser.parse_args(sys.argv[1:])
  execute(args)
  


  

